[package]
name = "AoE_2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name="day_1_sonar_sweep"
path="src/day_1_sonar_sweep/bin/main.rs"